# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/hlocal/jacynycz_serdes/jacynycz_serdes.srcs/sources_1/new/busloko.sv
  C:/hlocal/jacynycz_serdes/jacynycz_serdes.srcs/sources_1/imports/temp/definitions.sv
  C:/hlocal/jacynycz_serdes/jacynycz_serdes.srcs/sources_1/new/scrambler.sv
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/hlocal/jacynycz_serdes/jacynycz_serdes.cache/wt [current_project]
set_property parent.project_dir C:/hlocal/jacynycz_serdes [current_project]
catch { write_hwdef -file scrambler.hwdef }
synth_design -top scrambler -part xc7vx485tffg1157-1
write_checkpoint scrambler.dcp
report_utilization -file scrambler_utilization_synth.rpt -pb scrambler_utilization_synth.pb
